shell = "zsh"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.alias-tips]
github= "djui/alias-tips"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
