#!/bin/bash
day_num=$(date "+%u")

if [ $day_num == 1 ]; then
	day="Lundi"
elif [ $day_num == 2 ]; then
	day="Mardi"
elif [ $day_num == 3 ]; then
	day="Mercredi"
elif [ $day_num == 4 ]; then
	day="Jeudi"
elif [ $day_num == 5 ]; then
	day="Vendredi"
elif [ $day_num == 6 ]; then
	day="Samedi"
else
	day="Dimanche"
fi
echo $day;